name: Build

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize energy estimation
        uses: green-coding-berlin/eco-ci-energy-estimation@v4.0-rc3
        with:
          task: start-measurement
        continue-on-error: true

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout repo measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v4.0-rc3
        with:
          task: get-measurement
          label: "Repo checkout"
        continue-on-error: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup node measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v4.0-rc3
        with:
          task: get-measurement
          label: "setup node"
        continue-on-error: true

      - name: Install dependencies
        run: npm i

      - name: npm i measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v4.0-rc3
        with:
          task: get-measurement
          label: "npm i"
        continue-on-error: true

      - name: Build
        run: npm run build

      - name: build measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v4.0-rc3
        with:
          task: get-measurement
          label: "build"
        continue-on-error: true

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Show Energy Results
        uses: green-coding-berlin/eco-ci-energy-estimation@v4.0-rc3
        with:
          task: display-results
          pr-comment: true
        continue-on-error: true
